name = "ConvTools"
uuid = "4c0fc2cc-4405-4c84-a40a-96d0d72e7ae2"
authors = ["Subeen Pang <subinbg@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
julia = "1.8"
